version: '3.7'

services:

  geohut:
    image: volleybuddy_api
    restart: unless-stopped
    container_name: volleybuddy_api
    build: ./
    ports:
      - 3007:3007

      
networks:
  default:
    external:
      name: my-net